services:
  redis:
    image: redis
    ports:
      - 6379:6379

  eventstore.db:
    container_name: "eventstore-brewup"
    image: eventstore/eventstore:23.10.1-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: brewup-data
        target: /var/lib/eventstore-brewup
      - type: volume
        source: brewup-logs
        target: /var/log/eventstore-brewup

volumes:
  brewup-data:
  brewup-logs: